---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: generic
  namespace: default
spec:
  type: slack
  channel: general
  address: http://mynotify.flux.svc.cluster.local
    secretRef:
  name: webhook-url
