---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynotifier
  namespace: flux
  labels:
    language: go
  annotations:
    flux-systemcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: mynotifier
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mynotifier
    spec:
      containers:
      - name: mynotifier 
        image: lenfree/flux-generic-notifier-webhook-alpha:v0.0.1-kubewatch
        ports:
        - containerPort: 8080
        command: ["bash"]
        args: ["-c", "make", "run"]
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mynotifier
  namespace: flux
  labels:
    name: mynotifier
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: mynotifier
  type: ClusterIP
