---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-deployment
  namespace: flux
  labels:
    language: elixir
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: notify-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notify-deployment
    spec:
      serviceAccountName: list-pods
      containers:
      - name: notify-deployment
        image: lenfree/notify_deployment:0.0.4
        ports:
        - containerPort: 5000
        env:
          - name: SECRET_KEY_BASE
            # This shoud not be in Git but since this is just for a spike, I can
            # live with this
            value: eglQNvZ2QqLT0dHnkTpErVrNvAJvGz73XwPqbuGxWNEU0GBLJP4p6z1MED+MWOlv
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: notify-deployment
  namespace: flux
  labels:
    name: notify-deployment
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: notify-deployment
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
 name: list-pods
 namespace: flux
rules:
- apiGroups: ["apps"]
  resources: ["pods", "replicationcontrollers","services","nodes", "configmaps", "deployments", "namespaces", "daemonsets","replicasets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: list-pods
  namespace: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-pods
subjects:
  - kind: ServiceAccount
    name: list-pods
    namespace: flux
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: list-pods
  namespace: flux
