---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
  labels:
    language: ruby
  annotations:
    fluxcd.io/automated: "true"
    changes: "fix args"
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: lenfree/hello-world:0.0.2
        ports:
          - containerPort: 8080
        command: ["bash"]
        args: ["-c", "make", "start"]
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
              cpu: "500m"
              memory: "256Mi"
        env:
        - name: VERSION
          value: 0.0.2
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
  labels:
    name: hello-world
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: hello-world
  type: ClusterIP
