---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubewatch
  namespace: flux
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers","services","nodes", "configmaps", "deployments", "namespaces", "daemonsets", "persistentvolumes", "serviceaccounts", "secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["pods", "replicationcontrollers","services","nodes", "configmaps", "deployments", "namespaces", "daemonsets","replicasets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["pods", "replicationcontrollers","services","nodes", "configmaps", "deployments", "namespaces", "daemonsets", "clusterroles", "ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubewatch
  namespace: flux
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewatch
subjects:
  - kind: ServiceAccount
    name: kubewatch
    namespace: flux
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
  namespace: flux
data:
  .kubewatch.yaml: |
    namespace: ""
    handler:
      webhook:
        enabled: true
        url: "http://equerry.flux.svc.cluster.local/api/deployment/events"
    resource:
      clusterrole: true
      configmap: true
      daemonset: true
      deployment: true
      ingress: true
      job: true
      namespace: true
      node: true
      persistentvolume: true
      pod: true
      replicaset: true
      replicationcontroller: true
      secret: true
      serviceaccount: true
      services: true
---
apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: flux 
spec:
  serviceAccountName: kubewatch
  containers:
  - image: docker.io/bitnami/kubewatch:0.1.0-debian-10-r133
    imagePullPolicy: Always
    name: kubewatch
    volumeMounts:
    - name: config-volume
      mountPath: /opt/bitnami/kubewatch
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
