---
apiVersion: v1
kind: Service
metadata:
  name: hello-go
  namespace: default
  labels:
    name: hello-go
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: hello-go
  type: ClusterIP
